### ISSUE TITLE
Some software window's title have no pop-up menu and  cannot be pinned

### ISSUE THREAD

**Issue by redaelyks** [AlexanderPro/SmartSystemMenu#135]
such as the remote assistance window of Todesk，chat window of QQ，Right click on the titles of the first two software windows, but no pop-up menu appears。

**Comment by AlexanderPro** [comment]
Hi @redaelyks,

If Todesk and QQ have no new items in the system menu, you can try to add process names to the createMenuOnInitEvent section in the SmartSystemMenu.xml file (Maybe this will help). If  Todesk and QQ do not have a system menu at all, then SSM will not be able to add new items to the menu. Some windows don't have  system menu, in this case I would recommend to use the [SmartContextMenu](https://github.com/AlexanderPro/SmartContextMenu) instead of SSM.

**Comment by redaelyks** [comment]
Can you combine the functions of the two softwares? No, SSM's window title right-click menu is very easy to use, but you can only use SCM when you encounter a window without a title. It would be perfect to combine the functions of SCM into SSM.

**Comment by bootlegseahorse** [comment]
> Can you combine the functions of the two softwares? No, SSM's window title right-click menu is very easy to use, but you can only use SCM when you encounter a window without a title. It would be perfect to combine the functions of SCM into SSM.

You can just launch the two softwares simultaneously, which is what I've always been doing
