### ISSUE TITLE
Startet Programs are always run with enhanced rights

### ISSUE THREAD

**Issue by Horst12** [AlexanderPro/SmartSystemMenu#15]
If I start a program from the context menu provided by SmatSystemMenu
it always starts with enhanced rights.
This should never happen by default and is a big security issue

**Comment by AlexanderPro** [comment]
Hi Horst12,

It is fixed in this version [1.7.4](https://github.com/AlexanderPro/SmartSystemMenu/releases/download/1.7.4/SmartSystemMenu_v1.7.4.zip)
All processes started from the context menu provided by SmartSystemMenu will have Medium Integrity. Unfortunately, a proccess will not be run if it requires elevation. I will probably fix it in the next versions too.
